spring.application.name=ProjectBlog
server.port=8080

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://root:731224@aziz.wk3rclx.mongodb.net/aziz?retryWrites=true&w=majority&appName=aziz
